- name: Make sure ansible-install dir exist
  win_file:
    path: '{{ ansible_install_dir }}'
    state: directory

- set_fact:
    machine_arch: "{{ 'x86' if ansible_env.PROCESSOR_ARCHITECTURE == 'x86' else 'x86_64' }}"

- name: Install winlogbeat to ship window event log
  win_chocolatey:
    name: winlogbeat
    state: present
    version: "{{ winlogbeat_version }}"

- name: Deploy winlogbeat config
  win_template:
    src: "winlogbeat.yml"
    dest: '{{ chocolatey_lib_path }}\winlogbeat\tools\winlogbeat-{{ winlogbeat_version }}-windows-{{ machine_arch }}\winlogbeat.yml'
  notify: Enable winlogbeat service

# This seems to be window bug. I use this ansible module or my own PS script to
# set password it always return InvalidCredentialsError but the password is
# actually changed.

# So we need to do two things. Fireup the instance first, and then manually get
# the password via aws console. Then re-run the playbook which select the
# spawned instance - provide the initial_password.
# From now on we no longer need initial_password.

- name: Set admin password
  win_user:
    name: Administrator
    password: "{{ admin_password }}"
    state: present
    update_password: always
  ignore_errors: yes
  when: initial_password is defined and initial_password
